# tasks file
---
- name: install
  ansible.builtin.apt:
    name: "{{ vim_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - vim
    - vim-install

- name: create configuration file
  ansible.builtin.template:
    src: etc/vim/vimrc.local.j2
    dest: "{{ item.value.dest }}/.vimrc"
    owner: "{{ item.value.owner | default('root') }}"
    group: "{{ item.value.group | default(item.value.owner) | default('root') }}"
    mode: "{{ item.value.mode | default('0644') }}"
  with_dict: "{{ vim_vimrc_destinations }}"
  tags:
    - configuration
    - vim
    - vim-configuration
